name: Profile Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  success:
    runs-on: ubuntu-latest

    steps:
      - name: Done
        run: |
          echo "Workflow executed successfully."
          echo "Nothing to do."
